"""changed property lessons v2

Revision ID: 16ec16fa22ba
Revises: 9bfa49e9cddc
Create Date: 2024-12-15 15:22:20.090837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16ec16fa22ba'
down_revision: Union[str, None] = '9bfa49e9cddc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
