"""unique [airs

Revision ID: 6b7e954930fb
Revises: ed27971a3d8b
Create Date: 2025-01-27 20:28:30.751960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b7e954930fb'
down_revision: Union[str, None] = 'ed27971a3d8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_person_post_uc', 'teacher_students', ['teacher_id', 'student_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_person_post_uc', 'teacher_students', type_='unique')
    # ### end Alembic commands ###
