"""roles

Revision ID: 872f0464e698
Revises: f8f5ab2199d5
Create Date: 2025-01-27 17:32:49.407175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '872f0464e698'
down_revision: Union[str, None] = 'f8f5ab2199d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'smwht')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('smwht', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
