"""roles

Revision ID: f600ceeadea4
Revises: 311248ca43d7
Create Date: 2025-01-27 18:17:44.940620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f600ceeadea4'
down_revision: Union[str, None] = '311248ca43d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    role = postgresql.ENUM('STUDENT', 'TEACHER', 'ADMIN', 'GUEST',name='role')
    role.create(op.get_bind())

    op.add_column('users', sa.Column('user_role', sa.Enum('STUDENT', 'TEACHER', 'ADMIN','GUEST', name='role'), nullable=False, server_default="GUEST"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_role')
    op.create_table('students',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name='students_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='students_pkey')
    )
    # ### end Alembic commands ###
