"""test

Revision ID: f8f5ab2199d5
Revises: 9ba2e724f781
Create Date: 2025-01-27 17:04:15.348443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8f5ab2199d5'
down_revision: Union[str, None] = '9ba2e724f781'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('smwht', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'smwht')
    # ### end Alembic commands ###
